{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Bortip metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Bortip{service=\"helloweb3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HelloWeb3 Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"helloweb3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Control Plane Status",
   "type": "stat",
   "description": "Indicates whether API Server, Scheduler or Controller manager is down.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Unschedulable",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "stat",
   "description": "This is true if there is insufficient memory on the node, which could cause the node to swap frequently.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "stat",
   "description": "This condition is true if there is insufficient disk space on the node.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "stat",
   "description": "True when there are too many processes running on the node, indicating a potential exhaustion of process identifiers (PIDs).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Network Unavailable",
   "type": "stat",
   "description": "Indicates that the network to the node is not correctly configured or not available.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "description": "Indicates that there are pods in failed phase",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Unknown Pods",
   "type": "stat",
   "description": "Indicates that there are pods in unknown phase",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Unscheduled Pods",
   "type": "stat",
   "description": "Indicates that there are pods that cannot be scheduled.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(kube_pod_status_scheduled{condition=\"false\"}[5m]))"
    }
   ]
  },
  {
   "title": "PVCs Full in 2 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{}[1d], 2 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 5 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (\n  (\n    kubelet_volume_stats_available_bytes{}\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{}[1d], 5 * 24 * 60 * 60) < 0)\n  )\n) or vector(0)\n"
    }
   ]
  },
  {
   "title": "PVCs Full in 1 Week - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Above 80%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{} )) >= (80 / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "PVCs in Pending State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{phase=\"Pending\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Lost State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{phase=\"Lost\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global CPU  Usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[$__rate_interval])) / sum(machine_cpu_cores)",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"}) / sum(machine_cpu_cores)",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"}) / sum(machine_cpu_cores)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Global RAM Usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"})) / sum(machine_memory_bytes)",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"}) / sum(machine_memory_bytes)",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"}) / sum(machine_memory_bytes)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Cluster Utilization",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[5m])))",
       "legendFormat": "CPU Usage (%)"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) / sum(node_memory_MemTotal_bytes{})",
       "legendFormat": "Mem Usage (%)"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[$__rate_interval]))",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"})",
       "legendFormat": "Limits"
      },
      { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total" }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"})",
       "legendFormat": "Real"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"})",
       "legendFormat": "Limits"
      },
      { "expr": "sum(machine_memory_bytes)", "legendFormat": "Total" }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Status by Node",
     "type": "table",
     "description": "This table shows health status of nodes.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable) by (node)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"}) by (node)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", status!=\"false\"}) by (node)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", status!=\"false\"}) by (node)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", status!=\"false\"}) by (node)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\", status!=\"false\"}) by (node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Resource Usage by Instance",
     "type": "table",
     "description": "This table shows the resources usage of all nodes",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "avg by (instance) (1-rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) OR on() vector(0)",
       "legendFormat": "CPU Usage (%)"
      },
      {
       "expr": "(sum(node_memory_Buffers_bytes{job=\"node-exporter\"}) by (instance) +  sum(node_memory_Cached_bytes{job=\"node-exporter\"}) by (instance)) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"}) by (instance) OR on() vector(0)",
       "legendFormat": "Memory Usage (%)"
      },
      {
       "expr": "sum by (instance) (1-rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) OR on() vector(0)",
       "legendFormat": "CPU Used"
      },
      {
       "expr": "count(node_cpu_seconds_total{job=\"node-exporter\",mode='system'}) by (instance) OR on() vector(0)",
       "legendFormat": "CPU Total (vCPU)"
      },
      {
       "expr": "(sum(node_memory_MemTotal_bytes{job=\"node-exporter\"}) by (instance) - 0) / (1e9) OR on() vector(0)",
       "legendFormat": "Mem Total (GiB)"
      },
      {
       "expr": "(sum(node_memory_Buffers_bytes{job=\"node-exporter\"}) by (instance) + sum(node_memory_Cached_bytes{job=\"node-exporter\"}) by (instance)) / (1e9) OR on() vector(0)",
       "legendFormat": "Mem Used (GiB)"
      },
      {
       "expr": "sum(time() - node_boot_time_seconds{job=\"node-exporter\"}) by (instance) OR on() vector(0)",
       "legendFormat": "Uptime"
      },
      {
       "expr": "100 - (sum by (instance) (node_filesystem_avail_bytes{job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / sum by (instance) (node_filesystem_size_bytes{job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(node_filesystem_size_bytes{mountpoint=\"/\"}) by (instance) - sum(node_filesystem_free_bytes{mountpoint=\"/\"}) by (instance)) / 1e9",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum (node_filesystem_size_bytes{mountpoint=\"/\"}) by (instance) / 1e9",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(node_memory_SwapTotal_bytes{job=\"node-exporter\"}) by (instance) - sum(node_memory_SwapFree_bytes{job=\"node-exporter\"}) by (instance)) / (sum(node_memory_SwapTotal_bytes{job=\"node-exporter\"}) by (instance)) * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(node_memory_SwapTotal_bytes{job=\"node-exporter\"}) by (instance) - sum(node_memory_SwapFree_bytes{job=\"node-exporter\"}) by (instance))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(node_memory_SwapTotal_bytes{job=\"node-exporter\"}) by (instance))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Resource Commitment by Node",
     "type": "table",
     "description": "This table shows the resource requests and limits by pods deployed on specific node and their commitment level to node's resources.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests{unit=\"core\"}\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_limits{unit=\"core\"}\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests{unit=\"core\"}\n) / on(node) group_left() node:node_num_cpu:sum",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_limits{unit=\"core\"}\n) / on(node) group_left() node:node_num_cpu:sum",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests{unit=\"byte\"}\n) / 1e9",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_limits{unit=\"byte\"}\n) / 1e9",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests{unit=\"byte\"}\n) / on(node) group_left() node_memory_MemTotal_bytes:sum",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk (Free)",
     "type": "table",
     "description": "The table shows available disk size by mount points. Only mount point that used over 50% are displayed.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum(node_filesystem_free_bytes{fstype!=\"\"}) by (instance, fstype, mountpoint)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (instance, fstype, mountpoint) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(kube_pod_owner{job=\"kube-state-metrics\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{}) by (workload, namespace)) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Failed\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(avg_over_time(kube_pod_status_scheduled{condition=\"false\"}[5m])) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}) by (namespace) / sum(namespace_memory:kube_pod_container_resource_requests:sum{}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}) by (namespace) / sum(namespace_memory:kube_pod_container_resource_limits:sum{}) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{}) by (namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_limits:sum{}) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(namespace_workload_pod:kube_pod_owner:relabel{}) by (workload, workload_type, namespace)"
      },
      {
       "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n  kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type, namespace)\n/sum(\n  kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type, namespace)\n"
      },
      {
       "expr": "sum(\n  kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n/sum(\n  kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(namespace_workload_pod:kube_pod_owner:relabel{}) by (workload, workload_type, namespace)"
      },
      {
       "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n  kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n/sum(\n  kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n  kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      },
      {
       "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n/sum(\n  kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{}\n) by (workload, workload_type)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Quota",
     "type": "table",
     "description": "This table shows the CPU quota of pods in a namespace, shows only those that there CPU Requests (%) is greater then 80% and CPU Limits (%) is greater then 60%",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace,pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{}) by (namespace,pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace, pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{}) by (namespace, pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{}) by (namespace, pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace, pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{}) by (namespace, pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "description": "This table shows the Memory quota of pods in a namespace, shows only those that there Memory Requests (%) is greater then 80% and Memory Limits (%) is greater then 60%",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) by (namespace, pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{}) by (namespace,pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) by (namespace, pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{}) by (namespace,pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{}) by (namespace,pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) by (namespace,pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{}) by (namespace,pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PersistentVolumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent Volume Claim",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{})"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{}/1024/1024/1024)"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{}/1024/1024/1024)"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{}/1024/1024/1024)"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{}/kubelet_volume_stats_capacity_bytes{} * 100)"
      }
     ]
    }
   ]
  },
  {
   "title": "API Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 207 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"apiserver\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Deprecated Kubernetes Resources",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 207 },
     "targets": [
      {
       "expr": "apiserver_requested_deprecated_apis",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Summary by Instance",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 215 },
     "targets": [
      {
       "expr": "sum (rate(process_cpu_seconds_total{job=\"apiserver\"}[5m])) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum (process_resident_memory_bytes{job=\"apiserver\"}) by (instance) / (1024 * 1024 * 1024)",
       "legendFormat": "Mem Usage (GiB)"
      },
      {
       "expr": "sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\"}[5m])) by (instance) / 1000",
       "legendFormat": "Request Duration (s)"
      },
      {
       "expr": "sum (rate(apiserver_request_total{job=\"apiserver\", code=~\"5..\"}[5m])) by(instance)",
       "legendFormat": "Error Rate Last 5min (e/s)"
      },
      {
       "expr": "sum(rate(workqueue_depth{job=\"apiserver\"}[5m])) by (instance)",
       "legendFormat": "Work Queue"
      }
     ]
    },
    {
     "title": "Summary by Verb",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 220 },
     "targets": [
      {
       "expr": "sum by (verb) (rate(apiserver_request_total[5m])) OR on() vector(0)",
       "legendFormat": "Requests (req/s)"
      },
      {
       "expr": "sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\"}[5m])) by (verb) OR on() vector(0)",
       "legendFormat": "Request Latency (ms)"
      },
      {
       "expr": "sum by(verb) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\"}[5m]))\n / sum by(verb) (rate(apiserver_request_total{job=\"apiserver\"}[5m])) OR on() vector(0)",
       "legendFormat": "Error Rate Last 5min (e/s)"
      }
     ]
    }
   ]
  }
 ]
}